<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.const-x</groupId>
        <artifactId>toolbox</artifactId>
        <version>1.0.2-SNAPSHOT</version>
    </parent>

    <artifactId>console_ext</artifactId>
    <name>Console Ext</name>

    <description>Extended console utilities.</description>

    <dependencies>
        <dependency>
            <groupId>io.github.const-x</groupId>
            <artifactId>console</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.69</version>
        </dependency>

    </dependencies>

</project>
